Cleanup, replace go-etcd, save machine data
- Add comments
- Replace go-etcd for regular HTTP GET Request since go-etcd was having random
  error: "501: All the given peers are not reachable (Tried to connect to each
  peer twice and failed) [0]"
- Create custom structs to store machine information